name: AppKettle
description: "A small addon which allows you to control your AppKettle through Home Assistant.  Important note: you must block internet access for you AppKettle to force it into local mode.  This can be done in several ways, including using a firewall or a router.  If you do not block internet access, the kettle will not permit local connections and will not be able to be controlled."
version: "1.0.4"
url: "https://github.com/longmover/ha_addons"
slug: "appkettle_mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
homeassistant_api: true
host_network: true
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_usr: ""
  mqtt_pwd: ""
  min_lvl: 160
  max_lvl: 1640
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_usr: str
  mqtt_pwd: password
  min_lvl: int
  max_lvl: int
